// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Secrets struct {
	ID             uuid.UUID    `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	Path           string       `json:"path"`
	EncryptedValue []byte       `json:"encrypted_value"`
	Nonce          []byte       `json:"nonce"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type SharingRules struct {
	ID          uuid.UUID    `json:"id"`
	OwnerEmail  string       `json:"owner_email"`
	TargetEmail string       `json:"target_email"`
	Path        string       `json:"path"`
	Permission  string       `json:"permission"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Users struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	Name         string       `json:"name"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
