// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type HmacKeys struct {
	ID        uuid.UUID    `json:"id"`
	Key       []byte       `json:"key"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	IsActive  sql.NullBool `json:"is_active"`
}

type SecretVersions struct {
	ID             uuid.UUID     `json:"id"`
	SecretID       uuid.UUID     `json:"secret_id"`
	Version        int32         `json:"version"`
	EncryptedValue []byte        `json:"encrypted_value"`
	Nonce          []byte        `json:"nonce"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
	HmacSignature  []byte        `json:"hmac_signature"`
	HmacKeyID      uuid.NullUUID `json:"hmac_key_id"`
}

type Secrets struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Path      string       `json:"path"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type SharingRules struct {
	ID          uuid.UUID    `json:"id"`
	OwnerEmail  string       `json:"owner_email"`
	TargetEmail string       `json:"target_email"`
	Path        string       `json:"path"`
	Permission  string       `json:"permission"`
	CreatedAt   sql.NullTime `json:"created_at"`
	SharedUntil sql.NullTime `json:"shared_until"`
}

type Users struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	Name         string       `json:"name"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
