// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckIfShared(ctx context.Context, arg CheckIfSharedParams) (bool, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secrets, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteExpiredSecrets(ctx context.Context) error
	DeleteExpiredSharingRules(ctx context.Context) error
	GetAllSecretsForUser(ctx context.Context, userID uuid.UUID) ([]Secrets, error)
	GetPermissions(ctx context.Context, arg GetPermissionsParams) (string, error)
	GetSecretByPath(ctx context.Context, path string) (Secrets, error)
	GetSecretsSharedWithMe(ctx context.Context, targetEmail string) ([]GetSecretsSharedWithMeRow, error)
	GetSharedWith(ctx context.Context, arg GetSharedWithParams) ([]GetSharedWithRow, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Users, error)
	ShareSecret(ctx context.Context, arg ShareSecretParams) (SharingRules, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secrets, error)
}

var _ Querier = (*Queries)(nil)
