// not generated by sqlc
package db

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/pixperk/vaultify/internal/util"
)

type Store struct {
	*Queries
	db *sql.DB
}

func NewStore(db *sql.DB) *Store {
	return &Store{
		db:      db,
		Queries: New(db),
	}
}

func (store *Store) ExecTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	q := New(tx)
	err = fn(q)
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %v, rollback err: %v", err, rbErr)
		}
		return err
	}

	return tx.Commit()
}

func (s *Store) RotateHmacKey(ctx context.Context, staleDuration time.Duration) error {
	activeKey, err := s.GetActiveHMACKey(ctx)
	if err != nil && err != sql.ErrNoRows {
		return err
	}

	if staleDuration == 0 {
		staleDuration = 24 * time.Hour
	}

	// If active key exists and it's less than 24 hours old, skip rotation
	if err != sql.ErrNoRows && time.Since(activeKey.CreatedAt.Time) < staleDuration {
		return nil
	}

	// Start rotation
	return s.ExecTx(ctx, func(q *Queries) error {
		key, err := util.GenerateRandomKey(32)
		if err != nil {
			return err
		}

		if err := q.DeactivateAllHMACKeys(ctx); err != nil {
			return err
		}

		_, err = q.InsertHMACKey(ctx, key)
		return err
	})
}
